import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Heading from "@/app/Components/Heading";
import Navigation from "@/app/Components/Navigation";
import Banner from "./Components/Banner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Heading />
        <Navigation />
        <Banner>Get 10% off on business signup</Banner>
        {children}
      </body>
    </html>
  );
}
